In [1]:
import numpy as np

i = np.array([100,200,300,400,500,600,700,800,900,1000])

print(i[0:5])


[100 200 300 400 500]


In [2]:
import numpy as np

i = np.array([10,20,30,40,50,60,70,80,90])

print(i[2:5])

[30 40 50]


In [3]:
import numpy as np

i = np.array([11,22,33,44,55,66,77,88,99])

print(i[3:])

[44 55 66 77 88 99]


In [4]:
import numpy as np

i = np.array([11,22,33,44,55,66,77,88,99])

print(i[:5])

[11 22 33 44 55]


In [5]:
import numpy as np

i = np.array([10,20,30,40,50,60,70,80,90])

print(i[-5:-2])



[50 60 70]


In [6]:
import numpy as np

i = np.array([11,22,33,44,55,66,77,88,99])

print(i[-3:-1])

[77 88]


In [8]:
import numpy as np

i = np.array([21,22,23,24,25,26,27,28,29])

print(i[:-5])

[21 22 23 24]


In [9]:
import numpy as np

i = np.array([1,2,3,4,5,6,7,8,9])

print(i[2:-4])

[3 4 5]


In [13]:
import numpy as np

i = np.array([10,20,30,40,50,60,70,80,90])

print(i[0:4:3])

[10 40]


In [15]:
import numpy as np

i = np.array([11,12,13,14,15,16,17,18,19,20])

print(i[0:7:3])

[11 14 17]


In [16]:
print(i[::])

[11 12 13 14 15 16 17 18 19 20]


In [17]:
print(i[::2])

[11 13 15 17 19]


In [18]:
import numpy as np

i = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100]
])

print(i[1,0:3])

[60 70 80]


In [19]:
print(i[0,1:4])

[20 30 40]


In [21]:
import numpy as np

i = np.array([
    [11,22,33,44,55],
    [66,77,88,99,12],
    [10,20,30,40,50]
])

print(i[1,2:4])

[88 99]


In [29]:
print(i[0:3,3])

[44 99 40]


In [31]:
i = np.array([
    [10,20,30,40,50,60],
    [11,22,33,44,55,66],
    [1,2,3,4,5,6,]
])

print(i[0:2,2])

[30 33]


In [35]:
print(i[0:2,0:2])

[[10 20]
 [11 22]]


In [36]:
print(i[0:3,-3:-1])

[[40 50]
 [44 55]
 [ 4  5]]


In [37]:
print(i.dtype)

int32


In [38]:
import numpy as np

i = np.array([11,22,33,44,55,66])

print(i.dtype)

int32


In [40]:
import numpy as np

i = np.array([11,44,76,96,34,97,54])

s = i.astype("f")

print(s)

print(s.dtype)

print(i)

[11. 44. 76. 96. 34. 97. 54.]
float32
[11 44 76 96 34 97 54]


In [41]:
import numpy as np

i = np.array([14.5,5.6,54.5,89.7,])

s = i.astype(int)

print(s)

print(s.dtype)



[14  5 54 89]
int32


In [45]:
import numpy as np

i = np.array([10,24.5,0.0,6,87,96.7,0])

s = i.astype(bool)

print(s)

print(s.dtype)

[ True  True False  True  True  True False]
bool
